import {PartialLayout} from "app/layoutManager/LayoutManager";
const header: PartialLayout = {
    name: "header",
    extend: "desktopLayout",
    width: "100%",
    height: "10%",
    display: "fixed",
    layouts: [
        {
            name: "logo",
            width: "100%",
            height: "100%",
            scaleBy: "fit.in",
            alignIn: "c",
            align: "b",
            avoidBounding: "yes",
        },
    ],
};
const footer: PartialLayout = {
    name: "footer",
    extend: "desktopLayout",
    width: "125%",
    height: "40%",
    display: "fixed",
    align: "b",
    top: "12.5%",
    left: "2%",
    layouts: [
        {
            name: "footer_content",
            width: "100%",
            height: "100%",
            scaleBy: "fit.in",
            alignIn: "c",
            layouts: [
                {
                    name: "btns_con",
                    width: "100%",
                    height: "100%",
                    top: "6%",
                    layouts: [
                        {
                            name: "options_btn",
                            width: "40%",
                            height: "40%",
                            scaleBy: "fit.in",
                            avoidBounding: "yes",
                            alignIn: "c",
                            align: "b",
                            left: "45%",
                            top: "-35%",
                            layouts: [
                                {
                                    name: "options_selector",
                                    width: "200%",
                                    height: "400%",
                                    scaleBy: "fit.in",
                                    alignIn: "c",
                                    align: "c",
                                    top: "-250%",
                                },
                            ],
                        },
                        {
                            name: "balance_label",
                            avoidBounding: "yes",
                            alignIn: "c",
                            align: "b",
                            scaleBy: "fit.in",
                            width: "60%",
                            height: "40%",
                            left: "48%",
                            top: "-35%",
                        },
                        {
                            name: "win_label",
                            avoidBounding: "yes",
                            alignIn: "c",
                            align: "b",
                            scaleBy: "fit.in",
                            width: "60%",
                            height: "40%",
                            left: "108%",
                            top: "-35%",
                        },
                        {
                            name: "bet_selector",
                            width: "110%",
                            height: "40%",
                            avoidBounding: "yes",
                            alignIn: "c",
                            align: "b",
                            scaleBy: "fit.in",
                            left: "175%",
                            top: "-36.5%",
                        },
                        {
                            name: "messageBar",
                            width: "350%",
                            height: "25%",
                            avoidBounding: "yes",
                            scaleBy: "fit.in",
                            alignIn: "c",
                            left: "-211%",
                            top: "15.5%",
                        },
                        {
                            name: "autoplay_btn",
                            width: "40%",
                            height: "40%",
                            avoidBounding: "yes",
                            alignIn: "c",
                            align: "b",
                            left: "147%",
                            top: "-35%",
                            scaleBy: "fit.in",
                        },
                        {
                            name: "spin_btn",
                            width: "80%",
                            height: "80%",
                            avoidBounding: "yes",
                            alignIn: "c",
                            align: "c",
                            left: "-10%",
                            top: "-15%",
                            scaleBy: "fit.in",
                        },
                        {
                            name: "bet_btn",
                        },
                    ],
                },
            ],
        },
    ],
};
const gameBody: PartialLayout = {
    name: "gameBody",
    extend: "desktopLayout",
    display: "fixed",
    alignIn: "c",
    align: "c",
    width: 1600,
    height: 1080,
    layouts: [
        header,
        {
            name: "reelBox",
            height: "70%",
            width: "100%",
            scaleBy: "fit.in",
            alignIn: "c",
            align: "c",
            top: "-5%",
            layouts: [
                {
                    name: "autoplay_selector",
                    width: "40%",
                    height: "25%",
                    avoidBounding: "yes",
                    alignIn: "c",
                    align: "c",
                },
            ],
        },
        footer,
    ],
};
const desktopLayout: PartialLayout = {
    name: "desktopLayout",
    display: "relative",
    width: 1920,
    height: 1440,
    sortBy: "vertical",
    align: "c",
    layouts: [
        gameBody,
    ],
};

export default desktopLayout;
